# 服务器端口号
server:
  port: 8082


# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gdpushop?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid连接池
  #rabbitmq主机配置
  rabbitmq:
    host: 192.168.10.100
    username: root
    password: 123456
    port: 5672

#定义rabbitmq所需的名字
gdpu:
  dlx:
    exchange: gdpu_order_dlx_exchange
    queue: gdpu_order_dlx_queue
    routingKey: dlx
  order:
    exchange: gdpu_order_exchange
    queue: gdpu_order_queue
    routingKey: gdpu.order

#Mabatis-Plus
# SQL 日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1     # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  #===============redis配置===============
  redis:
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    #连接超时时间（毫秒）
    timeout: 1800000

    lettuce:
      pool:
        #连接池最大连接数（负值表示无限制）
        max-active: 20
        #最大阻塞等待时间（负数表示无限制）
        max-wait: -1
        #最大空闲连接
        max-idle: 5
        #最小空闲连接
        min-idle: 0